extends SceneTree
const Model=preload("res://scripts/bbq/model.gd")
const Sites=preload("res://scripts/bbq/sites.gd")
var failures:Array=[]
func check(ok:bool,message:String) -> void:
 if not ok:failures.append(message);push_error(message)
func _initialize() -> void:
 var m=Model.new()
 check(Sites.SITES.size()==10,"All ten waters, including the maritime additions, have gathering spots")
 for location in Sites.SITES:
  check(m.start(location),"Every location can start independently")
  check(m.start(location) and m.stations[location].items.size()==10,"Concurrent starts share one bounded kit")
 check(not m.start("invented"),"Unknown location rejected")
 var l:="secluded_beach"
 check(m.apply(l,2,0,"grab",6),"Client may take first tongs")
 check(not m.apply(l,3,0,"grab",6),"Two clients cannot own the same tongs")
 check(m.apply(l,3,1,"grab",7),"Second cook can join")
 check(not m.apply(l,2,0,"grab",8),"One prop per hand")
 check(not m.apply(l,4,1,"cook",0),"Cooking requires held tongs")
 check(m.apply(l,2,0,"cook",0,Sites.grill(1)),"First cook loads central heat")
 check(m.apply(l,3,1,"cook",1,Sites.grill(0)),"Second cook loads cooler edge")
 m.tick(45,[l])
 check(m.stations[l].items[0].cook[0]>m.stations[l].items[1].cook[0],"Heat zones differ")
 check(m.apply(l,2,0,"cook",0),"Turn first food")
 m.tick(45,[l])
 check(Model.doneness(m.stations[l].items[0]).begins_with("Golden"),"Both sides cook independently")
 check(m.apply(l,2,0,"cook",0),"Serve food")
 check(m.stations[l].items[0].place=="served","Served food leaves heat")
 check(m.apply(l,4,1,"grab",0),"Observer joins by taking a serving")
 check(not m.apply(l,3,1,"drop",0),"Other player cannot steal or drop held serving")
 check(m.apply(l,4,1,"drop",0),"Serving returns to communal plate for handoff")
 check(m.apply(l,5,0,"grab",0) and m.apply(l,5,0,"eat",0),"Another player can take and eat shared food")
 m.tick(3.1,[l]);check(m.stations[l].items[0].place=="pantry","Free ingredients replenish")
 check(not m.apply(l,4,1,"grab",8),"Closed cooler prevents taking hidden cans")
 check(m.apply(l,4,1,"cooler",-1),"Cooler opening belongs to shared station")
 check(m.apply(l,4,1,"grab",8) and m.apply(l,4,1,"sip",8),"Open drink")
 for i in 3:check(m.apply(l,4,1,"sip",8),"Sip drink")
 check(m.stations[l].items[8].place=="gone","Empty drink cleans up")
 m.release_peer(2);check(m.held(l,2,0)==-1,"Disconnect returns owned tools")
 m.tick(200,[]);check(m.stations.is_empty(),"Unattended stations pack away")
 print("BBQ_MODEL ",JSON.stringify({"failures":failures}));quit(0 if failures.is_empty() else 1)
